#!/usr/bin/env bash
# Note: this requires a _manual_ update on macos build runners
set -e

_cleanup(){
  exit -1
}

trap "_cleanup" INT

if ! (pwd | grep -E "^/Users/runner/builds/[a-zA-Z]{7,10}/[0-9]{1,3}/voteflux/voting_app$"); then
  echo "Error: not in correct directory." >&2
  exit 99
fi

export PATH="$HOME/flutter/bin:$PATH"
export ANDROID_HOME="/Library/Android/sdk"

sudo -u runner chmod -R g=u `pwd` 2>/dev/null || true
chmod -R g=u `pwd` 2>/dev/null || true
umask 0002

if [[ "$GITLAB_CI" == "true" ]]; then
  # rm -f ./.packages || true
  flutter upgrade
  flutter clean || true
  flutter pub cache repair
  # flutter pub get
fi

# cocoapods complains if this isn't set
export LANG=en_US.UTF-8

touch .packages
sudo chmod -R g+w ./

set -x
flutter build ios --verbose
cd ios
xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build -allowProvisioningUpdates
